version: "3"
services:
  front:
    build:
      context: .
      dockerfile: ./frontend/build/Dockerfile
    container_name: react_app
    tty: true
    volumes:
      - ./frontend:/app/react
    command: sh -c "cd /app/react  && yarn start"
    ports:
      - 3000:3000
  api:
    build:
      context: .
      dockerfile: ./backend/build/Dockerfile
    container_name: go_api
    tty: true
    volumes:
      - ./backend:/go/src/app
