version: "3"
services:
  react:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: react_app
    tty: true
    volumes:
      - ./frontend:/app/react
    command: sh -c "cd /app/react  && yarn start"
    ports:
      - 3000:3000
